LINUX_API_HEADERS_NAME := linux-api-headers
LINUX_API_HEADERS_VERSION := 4.17.11-1
LINUX_API_HEADERS_DESCRIPTION := Kernel headers sanitized for use in userspace

LINUX_API_HEADERS_FILES = $(shell find $(CACHE_PATH)/$(LINUX_API_HEADERS_NAME))
LINUX_API_HEADERS_TARGET_FILES = $(LINUX_API_HEADERS_FILES:$(CACHE_PATH)/$(LINUX_API_HEADERS_NAME)%=$(TARGET_PATH)%)

.PHONY: $(TARGETS:%=%_$(LINUX_API_HEADERS_NAME))

sync_nodeps_$(LINUX_API_HEADERS_NAME):
	mkdir -p $(CACHE_PATH)/$(LINUX_API_HEADERS_NAME)
	rsync -az --delete $(SOURCE_PREFIX)/cache/$(LINUX_API_HEADERS_NAME)/$(LINUX_API_HEADERS_VERSION)/ $(CACHE_PATH)/$(LINUX_API_HEADERS_NAME)

sync_$(LINUX_API_HEADERS_NAME): $(LINUX_API_HEADERS_DEPENDENCIES:%=sync_%) sync_nodeps_$(LINUX_API_HEADERS_NAME)

copy_nodeps_$(LINUX_API_HEADERS_NAME):
	rsync -a $(CACHE_PATH)/$(LINUX_API_HEADERS_NAME)/ $(TARGET_PATH)

copy_$(LINUX_API_HEADERS_NAME): $(LINUX_API_HEADERS_DEPENDENCIES:%=copy_%) copy_nodeps_$(LINUX_API_HEADERS_NAME)

ifdef LINUX_API_HEADERS_CONFLICTS
install_$(LINUX_API_HEADERS_NAME):
	@echo "error: installation of $(LINUX_API_HEADERS_NAME) would conflict with the following already installed packages: $(LINUX_API_HEADERS_CONFLICTS)"
	@exit 2
else
install_$(LINUX_API_HEADERS_NAME): $(LINUX_API_HEADERS_DEPENDENCIES:%=install_%) sync_$(LINUX_API_HEADERS_NAME) copy_$(LINUX_API_HEADERS_NAME)
	: >$(LIB_PATH)/installed/$(LINUX_API_HEADERS_NAME)
	echo "NAME=$(LINUX_API_HEADERS_NAME)" >> $(LIB_PATH)/installed/$(LINUX_API_HEADERS_NAME)
	echo "VERSION=$(LINUX_API_HEADERS_VERSION)" >> $(LIB_PATH)/installed/$(LINUX_API_HEADERS_NAME)
	echo "DESCRIPTION=$(LINUX_API_HEADERS_DESCRIPTION)" >> $(LIB_PATH)/installed/$(LINUX_API_HEADERS_NAME)
	echo "DEPENDENCIES=($(LINUX_API_HEADERS_DEPENDENCIES))" >> $(LIB_PATH)/installed/$(LINUX_API_HEADERS_NAME)
	echo "DEPENDANTS=($(LINUX_API_HEADERS_DEPENDANTS))" >> $(LIB_PATH)/installed/$(LINUX_API_HEADERS_NAME)
	echo "CONFLICTS=($(LINUX_API_HEADERS_CONFLICTS))" >> $(LIB_PATH)/installed/$(LINUX_API_HEADERS_NAME)
	echo "FILES=($(LINUX_API_HEADERS_TARGET_FILES))" >> $(LIB_PATH)/installed/$(LINUX_API_HEADERS_NAME)
	echo "LAST_UPGRADE_DATE=$$(date -Iseconds)" >> $(LIB_PATH)/installed/$(LINUX_API_HEADERS_NAME)
endif

remove_$(LINUX_API_HEADERS_NAME):
	rm -f $(LINUX_API_HEADERS_TARGET_FILES)

uninstall_cascade_$(LINUX_API_HEADERS_NAME): $(LINUX_API_HEADERS_DEPENDANTS:%=uninstall_cascade_%) remove_$(LINUX_API_HEADERS_NAME)

ifdef LINUX_API_HEADERS_DEPENDANTS
uninstall_$(LINUX_API_HEADERS_NAME):
	@echo "error: uninstallation of $(LINUX_API_HEADERS_NAME) would break the following packages which depend on it: $(LINUX_API_HEADERS_DEPENDANTS)"
	@exit 1
else
uninstall_$(LINUX_API_HEADERS_NAME): uninstall_cascade_$(LINUX_API_HEADERS_NAME)
	rm -f $(LIB_PATH)/installed/$(LINUX_API_HEADERS_NAME)
endif